### PR TITLE
Wiki CRUD completed

### PR DESCRIPTION
**Pull request by silvio-galli**
I modified a little bit from Bloc assignment and wireframe.

First of all, I didn't put `before_action authenticate_user!` in `app/controllers/application_controller.rb`. Instead I put `before_action authenticate_user!, except: [:index, :show]` in `app/controllers/wiki_controller.rb` so that even a guest user can take a look at the titles of wikis without interact with them. I put advices inviting him/her to sign up.

Clicking on wikis in top navigation bar, guest user will land here:

screenshot from 2016-03-11 12 08 07

Clicking on title guest user opens:

screenshot from 2016-03-11 12 08 36
where we have only the title of the wiki and guest user is adviced to sign in if he/she wants to read the wiki or to sign up if he/she didn't before.

Instead if the user signs in, will be redirect to `app/views/wikis/index` that I used as a "profile page" for the user (don't if it's a good practice, but I think that it can work for the moment):

screenshot from 2016-03-11 12 08 58

Where logged in user will find a list of his/her wikis and a list of other users wikis.

It's possible to edit or delete wikis directly form the table (only if the user is the author) or from the `show#view`:

screenshot from 2016-03-11 12 09 23

### CODE REVIEW

**Comment by silvio-galli** [comment]
I reset the db because I had a problem with the first wikis I created from `irb`; these wikis where without user so there was a problem with the show view.
Now that I have created two users with their wikis, everything works.

**Comment by silvio-galli** [comment]
I added Pundit and basic authorization policy.
If I try to `edit` a wiki that's not mine, this action raises a `Pundit::NotAuthorizedError` that's displayed in a

``` html
<div class="alert alert-danger">
  <p class="alert">You are not authorized to perform this action.</p>
</div>
```

**Comment by beaugaines** [comment]
Having `wikis#index` as your root path for a signed in user is a good and typical pattern, yes.  If you want to actually set it as a root route, follow directions [here](https://github.com/plataformatec/devise/wiki/How-To:-Define-a-different-root-route-for-logged-in-out-users)

Looks great so far!

**Comment by silvio-galli** [comment]
What does it mean when you close a pull request without merging it?
What am I supposed to do?

**Comment by beaugaines** [comment]
Sorry about that, I meant to merge it

**Pull request merged**
